<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SSchoolLibrary</AssemblyName>
    <ApplicationIcon>Assets\SSchoolLibrary.ico</ApplicationIcon>
    <Product>SSchoolLibrary</Product>
    <Version>2.0.0</Version>
    <Authors>Stephane Sob F.</Authors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SchoolLibrary\SchoolLibrary.csproj" />
  </ItemGroup>
</Project>
